### PR TITLE
AppVeyor Build Support

### PR DESCRIPTION
**Pull request by Jeavon**
I have configured this to use GitHub releases as the trigger to make a release as you have been using GitHub releases thus far.
Some notes:
- Populate the api keys for MyGet, GitHub & NuGet in appveyor.yml, ensure you encrypt the keys using the AppVeyor tool
- Ensure that your build number in appveyor.yml is set for the next release and also update it following a release so that new CI builds are shown as the next release version.
- All package data is now updated in package.proj only, package.xml & package.nuspec are just empty templates
- When making a release using the GitHub UI, ensure you publish it without any attached files, AppVeyor will append the Umbraco Zip package files automatically
- Avoid adding any annotated tags manually - these would not be considered a release (due to a bug in GitHub webhooks)
- If you want to perform a test build on a local machine you can execute test.bat, you can either enter the prompts or leave empty for default values

### CODE REVIEW

**Comment by leekelleher** [comment]
Thanks @Jeavon! A very big #h5yr! :sparkles::smiley::+1::boom::dancers::heart_eyes::metal::exclamation:

I'll review and merge during this week, (heavy schedule today/tomorrow).

**Comment by Jeavon** [comment]
You're very welcome! 

Gave me the chance to try out and break the new tag support in AppVeyor. It works perfectly if you use the GitHub UI or use lightweight tags but not annotated from a Git client/command line (I didn't actually know there were more than one type of tags in Git either). I think it's nicer than using a "Release" branch as you get the GitHub releases.

Skype me if you need any help with getting it setup.

**Comment by JimBobSquarePants** [comment]
Wizard! I'm gonna have a good look through this so I can learn your secrets!

**Comment by Jeavon** [comment]
Ha, no secrets, just bringing bits together, most of it is built on the good work of @mattbrailsford long ago

**Comment by leekelleher** [comment]
Thanks again @Jeavon!  Took me a few more days to get around to merging it in.

I'll let you know if I hit any issues with it.

**Comment by Jeavon** [comment]
No worries, I think my notes above explain most of the changes but Skype me if you need any help with setting up AppVeyor and the API keys etc...

**Comment by leekelleher** [comment]
@Jeavon I think I'll need to schedule a Skype chat with you - as I started looking over the AppVeyor stuff and I started to get the fear :cold_sweat: - I've no idea what I'm doing in there.

* Do I need to have MyGet set up?
* Do I need to change anything in the GitHub webhook?
* Which GitHub API key?

Sorry, I might sound stressed - I'm not (honest) :smile_cat: I'm just a little lost with it :confounded:

**Comment by Jeavon** [comment]
Sure thing, email me when you free, won't take long!

**Comment by mattbrailsford** [comment]
Happy to take a look once back from hols. Setup appveyor on another project
recently.

**Comment by leekelleher** [comment]
Thanks @Jeavon, I'll drop you an email.

I think I was trying to rush it earlier - juggling various things. I'll take another read of your 24days article too.

@mattbrailsford - cool, hopefully I'll have it sorted, but looking forward to catch up after your holiday.

**Comment by Jeavon** [comment]
No worries, slightly different to my 24days article as using the new GitHub tag support for release triggers. I'm around most of tomorrow and it should only take 10 minutes to get the right keys in there. I had it running perfectly on my own branch previously.

**Comment by leekelleher** [comment]
Thanks again @Jeavon for talking me through the process, all good now! #h5yr :hand:

**Comment by Jeavon** [comment]
Awesome, looking forward to seeing you AppVeyor badge soon :wink:

**Comment by Jeavon** [comment]
Love the badges! :clap:

**Comment by leekelleher** [comment]
Ace! (Where's the "like" button on GitHub comments?)

**Pull request merged**
