### PR TITLE
Custom DisposableTimer (for debug mode only)

### PR DESCRIPTION
**Pull request by leekelleher**
Following the discussion on #105, I have extended Umbraco's `DisposableTimer` class, (called `DittoDisposableTimer`), so that it will only attempt to time/profile whilst in debug mode.

> Note: This is a work-in-progress and needs further testing before merging in

### CODE REVIEW

**Comment by leekelleher** [comment]
Parking this for v0.9.0... I'm not confident enough with it to put it in v0.8.0 release.

**Comment by leekelleher** [comment]
@mattbrailsford @JimBobSquarePants I'd forgot about this... shall we merge it in and see how it goes?

**Comment by JimBobSquarePants** [comment]
Yeah, looks good to me and any performance boost is good.

**Comment by mattbrailsford** [comment]
Agreed 👍

**Pull request merged**
