### PR TITLE
Rename "Convert" to "Map" 

### PR DESCRIPTION
**Pull request by mattbrailsford**
As mentioned in issue #88 I've gone through and renamed usages of "Convert" to a "Map" alternative.

Do all of these now make sense?

* DittoMapHandler
* DittoMapHandlerContext
* DittoOnMappingAttribute
* DittoOnMappedAttribute
*  etc

I wasn't sure if DittoMapHandler / Context should be DittoMappingHandler (though that might cause confusion with Mapping / Mapped)

Matt

### CODE REVIEW

**Comment by leekelleher** [comment]
I'm not 100% sold on "Map" yet... I probably need to let it sink in.

Let's leave this open for a few days - if that's cool?

**Comment by mattbrailsford** [comment]
For sure, that's why I did it as a PR as wasn't entirely happy myself. Doesn't slow as nicely does it.

**Comment by mattbrailsford** [comment]
Only other "Map" option I can think of is the older style "OnBeforeMap" / "OnAfterMap"

**Comment by leekelleher** [comment]
The --ing and --ed follow Umbraco Core's conventions, (the Before/After were in v4 APIs)

**Comment by mattbrailsford** [comment]
Deciding against this

**Comment by leekelleher** [comment]
Shall we delete the `feature/convert-to-map` branch? or keep for reference?

No biggie either way, just doing some housekeeping :neckbeard:

**Pull request closed without merging**
