### PR TITLE
Generic Dictionary detected as Enumerable

### PR DESCRIPTION
**Pull request by leekelleher**
I've stumped up on a bug with how Ditto is determining if a property is an `Enumerable` type.

If a property is using a generic `Dictionary<T1, T2>` type, Ditto will attempt to cast the value as `Enumerable<T1>`.

I've added a unit-test to verify this scenario, see [`EnumerableDetectionTests`](https://github.com/leekelleher/umbraco-ditto/blob/bug/enumerable-detection/tests/Our.Umbraco.Ditto.Tests/EnumerableDetectionTests.cs), I think it's easier to explain in code.

Here's an example of the exception thrown...

```
Test Name:	GenericDictionary_Property_Is_Detected_As_Enumerable
Test FullName:	Our.Umbraco.Ditto.Tests.EnumerableDetectionTests.GenericDictionary_Property_Is_Detected_As_Enumerable
Test Source:	x:\umbraco-ditto\tests\Our.Umbraco.Ditto.Tests\EnumerableDetectionTests.cs : line 41
Test Outcome:	Failed
Test Duration:	0:01:52.941

Result Message:	System.ArgumentException : Object of type 'System.Linq.Enumerable+<CastIterator>d__b1`1[System.String]' cannot be converted to type 'System.Collections.Generic.Dictionary`2[System.String,System.String]'.
Result StackTrace:	
at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
at Our.Umbraco.Ditto.PublishedContentExtensions.ConvertContent(IPublishedContent content, Type type, CultureInfo culture, Object instance, IEnumerable`1 valueResolverContexts, Action`1 onConverting, Action`1 onConverted) in x:\umbraco-ditto\src\Our.Umbraco.Ditto\Extensions\PublishedContentExtensions.cs:line 383
at Our.Umbraco.Ditto.PublishedContentExtensions.As(IPublishedContent content, Type type, CultureInfo culture, Object instance, IEnumerable`1 valueResolverContexts, Action`1 onConverting, Action`1 onConverted) in x:\umbraco-ditto\src\Our.Umbraco.Ditto\Extensions\PublishedContentExtensions.cs:line 202
at Our.Umbraco.Ditto.PublishedContentExtensions.As[T](IPublishedContent content, CultureInfo culture, T instance, IEnumerable`1 valueResolverContexts, Action`1 onConverting, Action`1 onConverted) in x:\umbraco-ditto\src\Our.Umbraco.Ditto\Extensions\PublishedContentExtensions.cs:line 76
at Our.Umbraco.Ditto.Tests.EnumerableDetectionTests.GenericDictionary_Property_Is_Detected_As_Enumerable() in x:\umbraco-ditto\tests\Our.Umbraco.Ditto.Tests\EnumerableDetectionTests.cs:line 53
```

@JimBobSquarePants I've assigned it to you, as I think it is up your street.  Feel free to add to this `bug/enumerable-detection` branch with any fixes, etc.

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
A Dictionary is actually an `Enumerable<KeyValuePair>` so the detection is correct. I'll have a look at how the internal caster is handling it and work out a way to ensure we get the correct output.

**Comment by mattbrailsford** [comment]
Any luck with this @JimBobSquarePants?

**Comment by JimBobSquarePants** [comment]
Sorry @mattbrailsford  ... Not had the chance. I'll try and have a look in the next couple of hours.

**Comment by JimBobSquarePants** [comment]
@leekelleher @mattbrailsford That should be it fixed now guys.

**Comment by leekelleher** [comment]
Awesome, thanks @JimBobSquarePants - I'll give it a spin! :+1:

**Comment by JimBobSquarePants** [comment]
@leekelleher No problemo :sunglasses:

**Comment by leekelleher** [comment]
Coolio! :metal:

**Pull request merged**
