### PR TITLE
Umbraco Relation Resolver

### LINKED ISSUE #69: Umbraco Relation Resolver
Support for Umbraco Relations was originally raised in #36, but got lost in an evolving discussion.

The new `DittoValueResolver` approach can be used to easily support Relations.

### PR DESCRIPTION
**Pull request by leekelleher**
Support for Umbraco Relations was originally raised in #36, but got lost in an evolving discussion.

Closes #69

### CODE REVIEW

**Comment by leekelleher** [comment]
@Hendy Would be good to hear your thoughts on this, (no rush), especially around the usage of `RelationDirection`.

**Comment by Hendy** [comment]
Hi @leekelleher, I think the RelationDirection enum names make perfect sense, but maybe use the same language as the RelationTypes tree in Umbraco ?

* PartentToChild
* ChildToParent
* Bidirectional

**Comment by leekelleher** [comment]
:+1: Good call! Thanks for the sanity check @Hendy 

I haven't given these a good test yet, we'll see how it evolves during v0.8.0 dev :bowtie:

**Comment by mattbrailsford** [comment]
Can you use Enums within an Attribute?

**Comment by JimBobSquarePants** [comment]
@mattbrailsford Yeah, they're compile time constants so will work.

**Comment by mattbrailsford** [comment]
Cool, just wasn't sure. :+1:

**Comment by leekelleher** [comment]
Since I haven't had a need to use this on a website implementation myself, I am hesitant to merge it in.

I'm happy to leave this PR lingering around until there is a demand for it, (or if someone else wants to test it out).

**Comment by mattbrailsford** [comment]
Agreed

**Comment by JimBobSquarePants** [comment]
I still don't really understand relations so @Hendy this is one for you to test I guess...

**Comment by leekelleher** [comment]
Closing this PR.

I'm going to create a "contrib" project on the [labs repo](https://github.com/leekelleher/umbraco-ditto-labs), which this will be a good addition.

**Pull request closed without merging**
