### PR TITLE
TypeInitializationExtensions - use DependencyResolver?

### PR DESCRIPTION
**Pull request by leekelleher**
@JimBobSquarePants - Following on from #20 - do you see any issue with us swapping out using `Activator` with `DependencyResolver`?

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
As log as it falls back to `Activator` as the default then I think it's fine. In 99% cases I very much doubt anyone would be using dependency injection.

On the note of `TypeConverter`s I wanted to as whether we should establish a collection of built in converters for the various Umbraco datatypes. I already have working code for most of the main ones.

**Comment by leekelleher** [comment]
I agree, but now that the DI topic has been raised, it's how far do we go with it?

// @stevetemple - What are your thoughts on this? Is it an over-generalisation to be replacing every occurrence of `Activator.CreateInstance` with `DependencyResolver.Current.GetService`?

**Comment by JimBobSquarePants** [comment]
My spelling in that last comment was appalling!

I'd like to also consider performance as a factor in feature design so any insight on the impact of the change from that perspective would be most useful.

**Comment by leekelleher** [comment]
@JimBobSquarePants - It appears that the `GetService` of the default resolver (`DefaultDependencyResolver`) literally just calls `Activator.CreateInstance` (wrapped in a try/catch): 
[see here](https://github.com/ASP-NET-MVC/aspnetwebstack/blob/master/src/System.Web.Mvc/DependencyResolver.cs#L174).

re: Built-in TypeConverters (to ship with Ditto) ... sounds good, open a separate issue/PR.
Would this mean having built-in POCOs? (not as keen on that)

**Comment by JimBobSquarePants** [comment]
@leekelleher That's good to know. I would definitely us `DependencyResolver` in that instance then but leave any other `Activator.CreateInstance` usages throughout the codebase intact since they don't involve anything that we'd want too many people messing with.

re: Built-in TypeConverters. No POCO's are used in any implementations I have done but I couldn't be sure about if we tried to do grid or related links.

**Comment by stevetemple** [comment]
A good built in TypeConverter would be one for the new Grid stuff in 7.2

**Comment by leekelleher** [comment]
OK, let's open a new PR and see where we go with built-in TypeConverters :muscle:

**Comment by stevetemple** [comment]
One of the guys here is actually writing that grid `TypeConverter` already so we'll send that over once it's done

**Comment by leekelleher** [comment]
Cool, thanks @stevetemple!

**Comment by JimBobSquarePants** [comment]
Ace. I'll open a PR in an hour or so with a few.

**Pull request merged**
