### PR TITLE
API Documentation using Wyam

### PR DESCRIPTION
**Pull request by leekelleher**
As mentioned on #157, I've started prototyping our API documentation using Wyam.

This is completely open to discussion, as I want us all to be comfortable with it.

If you want to try it out locally, then here's what to do...

1. Checkout the "docs/wyam-prototype" branch
2. Go to the "/docs" folder...
  a. Run the "get-wyam.cmd" batch file, (this will download Wyam via NuGet)
  b. From a command-prompt, (in the "/docs" folder), run this...
    * `.wyam\Wyam.exe --watch --preview`

  c. Open a browser at <http://localhost:5080/>

I haven't added any CSS styling. For the markup, I've mostly took inspiration from the [Wyam.io](http://wyam.io) docs.

Like I say, this is totally open for discussion, I'm a believer in Cunningham's Law! :stuck_out_tongue_closed_eyes:

### CODE REVIEW

**Comment by leekelleher** [comment]
Given that GitHub Pages can now generate from the `/docs` folder, ([see their blog post about it](https://github.com/blog/2233-publish-your-project-documentation-with-github-pages)). We could switch back to using GitHub Pages/Jekyll for handling the docs?

As much as I like Wyam, I appreciate that it is another layer to the build process.

Thoughts?

**Comment by mattbrailsford** [comment]
After playing with wyam, I'd be inclined to agree. I think the only benefit it brings is being able to generate the API docs, but I'm guessing we might still be able to try and automate that in some way. Even if not, I think simplicity has to be key otherwise we just won't keep up to it.

**Comment by mattbrailsford** [comment]
If we do close this PR though, it's whether we need to re-open an issue to write the docs :)

**Comment by leekelleher** [comment]
Yeah, we'll close this one off, (no immediate rush though), but let's keep the branch until we've made a decision and/or have done the switch over. I'll create a separate issue for the Jekyll-based docs (or re-open the old one)

**Comment by leekelleher** [comment]
Closing this PR. Raised new issue #192

**Pull request closed without merging**
