### PR TITLE
Added a "cacheable" lazy check of the debug mode

### PR DESCRIPTION
**Pull request by tompipe**
Added a "cacheable" lazy check of the debug mode check

### CODE REVIEW

**Comment by mattbrailsford** [comment]
Can you explain the reason? What issue is it fixing?

**Comment by JimBobSquarePants** [comment]
Reading configuration values from the web.config is lazy and one time anyway as far as I'm aware. I'm not convinced the `ResettableLazy<TValue>.Reset()` method is threadsafe either.

**Comment by tompipe** [comment]
Ah you're right! I need to stop coding crazy ideas at 3am, or at least give them more thought! 😂

**Comment by mattbrailsford** [comment]
Gonna close this PR then, thanks anyways :)

**Comment by tompipe** [comment]
No worries, I saw Lee's TODO whilst I had the solution open anyway, and thought i'd try help out.

**Comment by mattbrailsford** [comment]
@tompipe your help is always welcome :)

**Comment by leekelleher** [comment]
Me and my TODO notes eh? (_it'll be my downfall_)

I think I added the note as we were calling `AppSettings["Ditto:DebugEnabled"]` twice, but I wasn't sure if that could be optimised on our side? (But going from @JimBobSquarePants's comment above, I've read up about it now and .NET does cache it already).

I'll remove the TODO note 😉

**Pull request closed without merging**
