### PR TITLE
Release 0.9.0-beta

### PR DESCRIPTION
**Pull request by leekelleher**
In preparation for v0.9.0 beta release.

### CODE REVIEW

**Comment by mattbrailsford** [comment]
Holy crap we did a lot in 0.9 :)

**Comment by leekelleher** [comment]
@mattbrailsford I thought it best to do a "beta" first, just to air on the side of caution :wink:

**Comment by jamiepollock** [comment]
I know we've had sleet & messed up weather here in the UK recently but is this release really Christmas comes early? ;)

**Comment by JimBobSquarePants** [comment]
Glad to see this getting shipped and also that this is beta, I've got another super performance trick to share on the property getters/setters. Looks like I can ramp up the speed another 25%. :racehorse: 

How are our docs looking? I can have a look and see which bits I can expand upon.

**Comment by leekelleher** [comment]
@jamiepollock Thanks! I'm gonna tweet about it today (I didn't get chance last night)

@JimBobSquarePants Cool, ace!! I'll get a release branch ready (from master), then we can add it to 0.9.0 ... If you want?

Re: Docs ... Latest is all in the /docs folder. I wrote up a page on how to upgrade to Processors in 0.9.0, but looks like ReadTheDocs didn't render it, which is worrying. :sad:

I'm swaying towards us using GitHub Pages (possibly using Wyam?). Would feel more self-contained and full control over the output.

**Pull request merged**
